version: '3.8'

services:
  mssql:
    build: .
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
